UPLOAD_FILE_DIR: '/uploads'
FILE_EXT: ['.jpeg', '.jpg']
FONT: '/app/static/fonts/arial.ttf'
FONT_SIZE: 20

DB_MASTER:
  USER: 'test'
  PORT: 5432
  PASS: 'qwerty1234'
  HOST: 'postgres'
  DB_NAME: 'testdb'

REDIS:
  HOST: 'redis'
  PORT: 6379
  PASS: 112233
  DB_NUM: 0

PORT: 6969