version: '3.8'

services:
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_DB: testdb
      POSTGRES_PASSWORD: qwerty1234
      POSTGRES_USER: test
    ports:
      - "5432:5432"

  redis:
      image: redis:5.0.5
      restart: unless-stopped
      ports:
        - "6379:6379"
      command: >
        --requirepass 112233
        
  application:
      container_name: python_app
      ports:
        - "6969:6969"
      build: .