version: '3.3'

services:
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_DB: testdb
      POSTGRES_PASSWORD: qwerty1234
      POSTGRES_USER: test
    ports:
      - "5432:5432"

  redis:
      image: redis:5.0.5
      restart: unless-stopped
      ports:
        - "6379:6379"
      command: >
        --requirepass 112233
        
  rest_app:
      container_name: rest_app
      ports:
        - "6969:6969"
      volumes:
        - uploads:/uploads
      depends_on:
        - postgres
        - redis
      command: bash -c "alembic upgrade head && python3 -u rest_app"
      build:
         context: .
         dockerfile: rest_app/Dockerfile

  image_handler:
      container_name: image_handler
      depends_on:
        - postgres
        - redis
      build:
          context: .
          dockerfile: image_handler/Dockerfile

  data_saver:
      container_name: data_saver
      volumes:
        - uploads:/uploads
      depends_on:
        - postgres
        - redis
      build:
          context: .
          dockerfile: data_saver/Dockerfile

volumes:
  uploads:
